### ISSUE TITLE
apt isn't able to execute from hassio command line

### ISSUE THREAD

**Issue by johanf85** [richardzone/homeassistant-dht#16]
Hi, would like to use this integration, I installed it via HACS., after adding it manually as a repository to the HACS store.   

However the setup instructions say to run:

`sudo apt install libgpiod2`

This cannot be done on my system, Home assistant OS, as I cannot execute `apt` on it. Apparently this commond is available on docker and other hosts, however not on HAOS. 

Right now I cannot get it to work.

**Comment by richardzone** [comment]
Hi, ibgpiod2 is required by this repo's dependency. I don't have HA OS setup but a quick google search would find: https://community.home-assistant.io/t/use-apt-get-commands/236873/28. Hope this helps.
