### ISSUE TITLE
dht can't install `RPi.GPIO==0.7.1a4`: error: command 'gcc' failed: No such file or directory

### ISSUE THREAD

**Issue by Bluscream** [richardzone/homeassistant-dht#25]
```
2022-12-15 00:42:00.063 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package RPi.GPIO==0.7.1a4: error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-310
      creating build/lib.linux-aarch64-cpython-310/RPi
      copying RPi/__init__.py -> build/lib.linux-aarch64-cpython-310/RPi
      creating build/lib.linux-aarch64-cpython-310/RPi/GPIO
      copying RPi/GPIO/__init__.py -> build/lib.linux-aarch64-cpython-310/RPi/GPIO
      running build_ext
      building 'RPi._GPIO' extension
      creating build/temp.linux-aarch64-cpython-310
      creating build/temp.linux-aarch64-cpython-310/source
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.10 -c source/c_gpio.c -o build/temp.linux-aarch64-cpython-310/source/c_gpio.o
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for RPi.GPIO
  error: subprocess-exited-with-error
  
  × Running setup.py install for RPi.GPIO did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running install
      /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-310
      creating build/lib.linux-aarch64-cpython-310/RPi
      copying RPi/__init__.py -> build/lib.linux-aarch64-cpython-310/RPi
      creating build/lib.linux-aarch64-cpython-310/RPi/GPIO
      copying RPi/GPIO/__init__.py -> build/lib.linux-aarch64-cpython-310/RPi/GPIO
      running build_ext
      building 'RPi._GPIO' extension
      creating build/temp.linux-aarch64-cpython-310
      creating build/temp.linux-aarch64-cpython-310/source
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> RPi.GPIO
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
2022-12-15 00:42:35.934 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hassio
```

## System Information

version | core-2022.12.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4952
Installed Version | 1.28.4
Stage | running
Available Repositories | 1227
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 5, 2023 at 1:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 57.8 GB
disk_used | 4.5 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | RPC Shutdown (2.2), File editor (5.4.2), ZeroTier One (0.15.2), Log Viewer (0.14.0), SSH & Web Terminal (13.0.0), Mosquitto broker (6.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 5, 2022 at 3:07 AM
-- | --
current_recorder_run | December 15, 2022 at 12:35 AM
estimated_db_size | 244.63 MiB
database_engine | sqlite
database_version | 3.38.5

</details>
[config_entry-hacs-2391e602c36bbc6ee74d84c721a96b8a.json.txt](https://github.com/richardzone/homeassistant-dht/files/10232521/config_entry-hacs-2391e602c36bbc6ee74d84c721a96b8a.json.txt)

**Comment by richardzone** [comment]
Hi, `gcc` is also required and needs to be installed
