### ISSUE TITLE
Is this working on latest Homeassistant?

### ISSUE THREAD

**Issue by gaRFio01** [richardzone/homeassistant-dht#3]
Is this compatible with latest versions of ha?

as far as I know, python versions used in the latest version did not work with this custom integration…

thanks!!!

**Comment by richardzone** [comment]
It should work - what error message / logs are you getting?

**Comment by gaRFio01** [comment]
https://community.home-assistant.io/t/dht-sensor-custom-components/390428/24 All this topic is talking about this.
