### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by tezcooling** [richardzone/homeassistant-dht#44]
The DHT sensor was working great for about a week. Now the reading never changes and I get the following in my log:

Source: custom_components/dht/sensor.py:193
Finished call to 'custom_components.dht.sensor.DHTClient.read_retry' after 0.354(s), this was the 1st time calling it.

My Setup:
DHT22 Wired to pin 4
powered from 3.3v
Raspberry pi 4
HAOS

Any ideas why it may have stopped working?

**Comment by richardzone** [comment]
Can you provide more logs?
