### ISSUE TITLE
Error correction

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [richardzone/homeassistant-dht#71]
Hi, does this library have any error correction? Sometimes I see spikes in temperature/humidity far from the actual values. Please fix this.

**Comment by Andrei-Iosifescu123** [comment]
![Screenshot_20230726_214059_io homeassistant companion android](https://github.com/richardzone/homeassistant-dht/assets/35394195/092854f7-b440-4275-b86f-b07d816216f6)

**Comment by richardzone** [comment]
Hi @Andrei-Iosifescu123  as I am no longer using this setup I'm unable to test and verify, but feel free to contribute PR and I'm happy to review.
